### ISSUE TITLE
failed job running through updated tutorial

### ISSUE THREAD

**Issue by pymonger** [EOEPCA/proc-ades#2]
Greetings. I was able to step through the updated wiki page up to here: https://github.com/EOEPCA/proc-ades/wiki/Submit%20a%20processing%20job. When I query for the job status, i get:

```
{
    "jobID": "0ddc5bd4-2b86-11ec-a485-36c49dae35c8",
    "started": "2021-10-12T17:58:49.980013Z",
    "status": "failed",
    "message": "Done",
    "progress": "100",
    "links": [
        {
            "href": "http://localhost:8080/soamc/watchjob/processes/snuggs-0_3_0/jobs/32a6100a-2b85-11ec-815e-36c49dae35c8/soamc/watchjob/processes/snuggs-0_3_0/jobs/0ddc5bd4-2b86-11ec-a485-36c49dae35c8",
            "rel": "self",
            "type": "application/json",
            "title": "get Status"
        }
    ]
}
```

The logs on the ADES pod show this:
```
127.0.0.1 - - [12/Oct/2021:18:01:53 +0000] "GET /soamc/wps3/processes/snuggs-0_3_0/jobs HTTP/1.1" 200 1061 "-" "-"
Execute POST
parsing cwl to retrieve the ResourceRequirements
inputs_content
{'inputs': [{'dataType': 'application/json',
             'href': '',
             'id': 'input_reference',
             'mimeType': '',
             'value': 'https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_36RTT_20191205_0_L2A'},
            {'dataType': 'application/json',
             'href': '',
             'id': 'input_reference',
             'mimeType': '',
             'value': 'https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2B_36RTT_20191215_0_L2A'},
            {'dataType': 'string',
             'href': '',
             'id': 's_expression',
             'mimeType': '',
             'value': 'nbr:(/ (- B05 B02) (+ B05 B02))'},
            {'dataType': 'string',
             'href': '',
             'id': 's_expression',
             'mimeType': '',
             'value': 'ndvi:(/ (- B05 B03) (+ B05 B03))'},
            {'dataType': 'string',
             'href': '',
             'id': 's_expression',
             'mimeType': '',
             'value': 'ndwi:(/ (- B06 B03) (+ B06 B03))'},
            {'dataType': 'string',
             'href': '',
             'id': 'ADES_APP',
             'mimeType': '',
             'value': 'ades'},
            {'dataType': 'string',
             'href': '',
             'id': 'job',
             'mimeType': '',
             'value': 'wf-696b5568-2b86-11ec-854f-36c49dae35c8'},
            {'dataType': 'string',
             'href': '',
             'id': 'outputfile',
             'mimeType': '',
             'value': 'wf-696b5568-2b86-11ec-854f-36c49dae35c8.res'}]}
/tmp/tmp2b2m5b98
/tmp/tmppxmpjes7
INFO:     127.0.0.1:41456 - "POST /execute HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/workflow_executor-1.0.6-py3.9.egg/workflow_executor/fastapiserver.py", line 376, in read_execute
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/workflow_executor-1.0.6-py3.9.egg/workflow_executor/execute.py", line 83, in run
    wrapped_cwl_document = wrapcwl(cwl_document, cwl_wrapper_config)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/workflow_executor-1.0.6-py3.9.egg/workflow_executor/execute.py", line 270, in wrapcwl
    wf = Parser(k)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/cwl_wrapper-0.8.0-py3.9.egg/cwl_wrapper/parser.py", line 43, in __init__
    self.out = self.blender.get_output()
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/cwl_wrapper-0.8.0-py3.9.egg/cwl_wrapper/blender.py", line 506, in get_output
    start = self.__add_stage_in_graph_cwl(start)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/cwl_wrapper-0.8.0-py3.9.egg/cwl_wrapper/blender.py", line 298, in __add_stage_in_graph_cwl
    self.main_stage_in['inputs'] = {}
TypeError: 'str' object does not support item assignment
```
I wanted to attempt to debug the issue myself because I'm somewhat familiar with Calrissian but I wasn't sure where to start. Now as I understand it, `proc-ades` utilizes Calrissian to execute the CWL workflows on Kubernetes however I did not see any Calrissian K8s jobs running in my cluster after I submitted the snuggs job. 

Should I expect to see them show up on my cluster or are they being executed on a K8s cluster somewhere else?
In regards to the error above, is there anything I need to fix on my end?

Thanks in advance.

**Comment by rconway** [comment]
Thanks for the further debug info. Will make an investigation and follow up.
