### ISSUE TITLE
WorkflowExecutor.processingNodeSelector missing in Helm Chart

### ISSUE THREAD

**Issue by JannesLathouwers** [EOEPCA/proc-ades#4]
When using the version 1.1.1 of the ADES there is an issue when trying to execute a workflow:
```
INFO:     127.0.0.1:46826 - "GET /prepare/python-sleeper-0-0-1a6a54a9a-9e1f-11ec-a8e0-0242ac110007 HTTP/1.1" 200 OK
Execute POST
INFO:     127.0.0.1:46830 - "POST /execute HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/conda/envs/workflow_executor_env/lib/python3.9/site-packages/workflow_executor-1.0.25-py3.10.egg/workflow_executor/fastapiserver.py", line 223, in read_execute
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
This is due to the missing configuration of WorkflowExecutor.processingNodeSelector in the Helm Chart.

**Comment by bbrauzzi** [comment]
The fix has been implemented and released in **proc-ades:1.1.2**
